FROM openjdk:8u181-jdk-alpine3.8

RUN apk update && \
    apk add --no-cache bash && \
    mkdir /web_service 

COPY app /web_service/app

WORKDIR /web_service/app/bin


ENTRYPOINT [ "./backend", "-Dplay.http.secret.key=preawjeed39"]

EXPOSE 9000